# NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

In [2]:
# I'm writing this again because of my mistake I lost all the content of this file which I wrote few hours ago. So sod :(

In [3]:
arr = np.array([-1, 2, 4])

In [4]:
brr = np.array([0, 3, -9])

In [5]:
# doing dot product of 'arr' & 'brr'
np.dot(arr, brr)

-30

In [6]:
# checking shape and size of 'arr'
arr.shape

(3,)

In [7]:
arr.dtype

dtype('int32')

In [8]:
# An array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# A zero matrix of 3x4
zero_mat = np.zeros((3, 4))
zero_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# changing all elements of 2nd row of 'zero_mat' to 7
zero_mat[2] = 7
zero_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [7., 7., 7., 7.]])

### Creating An Identity Matrix

In [11]:
Identity_mat = np.identity(4) # Identity matrix of 4x4

In [12]:
print(Identity_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
#changing all elements(a_[ij]) of 'Identity_mat' which are below diagonal to i+j.
Identity_mat[1:4]

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
for i in range(1, 4):
    for j in range(i):
        Identity_mat[i][j] = i+j

In [19]:
Identity_mat

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [2., 3., 1., 0.],
       [3., 4., 5., 1.]])

In [20]:
Identity_mat.dtype

dtype('float64')

### Arithmetic with NumPy Array

In [21]:
A_matrix = np.arange(10).reshape(2, 5)
A_matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
B_matrix = np.arange(20, 35).reshape(5, 3)

In [23]:
B_matrix

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34]])

In [24]:
# Matrix Multiplication of { A & B}_matrix
np.dot(A_matrix, B_matrix)

array([[ 290,  300,  310],
       [ 940,  975, 1010]])

In [25]:
1/B_matrix # reciprocal of each element

array([[0.05      , 0.04761905, 0.04545455],
       [0.04347826, 0.04166667, 0.04      ],
       [0.03846154, 0.03703704, 0.03571429],
       [0.03448276, 0.03333333, 0.03225806],
       [0.03125   , 0.03030303, 0.02941176]])

### Indexing and Slicing with Array

In [27]:
# getting elements of A_matrix 1st and 2nd column
A_matrix[0:, 3:]

array([[3, 4],
       [8, 9]])

In [28]:
# getting all elements of middle column of B_matrix
B_matrix[1, 0:]

array([23, 24, 25])

In [29]:
B_matrix[0:, 1]

array([21, 24, 27, 30, 33])

## Boolean Indexing

In [32]:
names = np.array(["lucky", "shubham", "ayan", "lucky", "john", "prince", "ayan", "shubham", "harry", "lucky"])
data = np.array([89, 70, 69, 99, 89, 87, 58, 72, 99, 85])

In [33]:
names

array(['lucky', 'shubham', 'ayan', 'lucky', 'john', 'prince', 'ayan',
       'shubham', 'harry', 'lucky'], dtype='<U7')

In [34]:
data

array([89, 70, 69, 99, 89, 87, 58, 72, 99, 85])

In [35]:
# now printing data corresponding to "lucky"
data[names == "lucky"]

array([89, 99, 85])

In [36]:
# corresponding to "ayan"
data[names == "ayan"]

array([69, 58])

In [37]:
names[(names == "lucky") | (names == "ayan") | (names == "shubham")]

array(['lucky', 'shubham', 'ayan', 'lucky', 'ayan', 'shubham', 'lucky'],
      dtype='<U7')

In [38]:
(names == "lucky") | (names == "ayan") | (names == "shubham")

array([ True,  True,  True,  True, False, False,  True,  True, False,
        True])

In [39]:
names.reshape(10, 1)

array([['lucky'],
       ['shubham'],
       ['ayan'],
       ['lucky'],
       ['john'],
       ['prince'],
       ['ayan'],
       ['shubham'],
       ['harry'],
       ['lucky']], dtype='<U7')

In [40]:
data.reshape(10, 1)

array([[89],
       [70],
       [69],
       [99],
       [89],
       [87],
       [58],
       [72],
       [99],
       [85]])

## Transposing Arrays 

In [41]:
''' 
let A be a 3x4 matrix and B be a 5x3 matrix,
It can be seen that we can't take dot product of A & B but we can
take B & A
'''
A = np.arange(12).reshape(3, 4)
B = np.arange(50, 65).reshape(5, 3)

In [42]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
B

array([[50, 51, 52],
       [53, 54, 55],
       [56, 57, 58],
       [59, 60, 61],
       [62, 63, 64]])

In [45]:
np.dot(B, A)

array([[ 620,  773,  926, 1079],
       [ 656,  818,  980, 1142],
       [ 692,  863, 1034, 1205],
       [ 728,  908, 1088, 1268],
       [ 764,  953, 1142, 1331]])

In [46]:
# Transpose of B 
B.T

array([[50, 53, 56, 59, 62],
       [51, 54, 57, 60, 63],
       [52, 55, 58, 61, 64]])